missing http status codes added
CrowCpp/Crow pull request #227
Opened 2021-09-29 17:32 UTC by Zhavok92

2021-09-29 23:35 UTC, The-EDev commented
I'm sorry for the late response, I was occupied with another PR, I have a few concerns about some of the codes added, I'll list them in the next comment.

2021-09-30 01:21 UTC, The-EDev requested changes
- `102` - webdav only
- `103` - seemingly no compatibility **(not sure what to do about it)**

- `207`, `208` - Webdav again
- `226` - Crow doesn't support delta encoding by default **(just a note)**

- `305`, `306` - Deprecated **(definitely remove)**

- `402`, `425` - Seems experimental **(not sure what to do about them)**
- `406` - Crow doesn't support Server-driven content negotiation by default **(just a note)**
- `408` - Crow shuts down connections without sending this, will require changes to `connection.h` **(definitely remove)**
- `411`, `412`, `414`, `421`, `426`, `431` - They feel like they shouldn't be sent by a user, rather by crow itself.. which crow doesn't send currently **(suggest removal)**
- `418` - Ummm... really? ... fine. **(just a note)**
- `422`, `423`, `424` - Webdav

- `504`, `505` - They feel like they shouldn't be sent by a user, rather by crow itself.. which crow doesn't send currently **(suggest removal)**
- `507`, `508` - Webdav once more
- `510` - Crow doesn't support HTTP extension **(suggest removal)**
- `511` - usually generated by proxies, crow is not meant to be a proxy **(definitely remove)**

For webdav codes, I suggest removing them since Crow neither supports webdav nor webdav HTTP methods, both can be added in a later PR if needed.

2021-09-30 09:49 UTC, Zhavok92 commented
Thanks for response, I have removed the changes you mentioned.

2021-09-30 13:02 UTC, The-EDev approved these changes

2021-09-30 13:03 UTC, merged