WIP CORS Middleware
CrowCpp/Crow pull request #348
Opened 2022-02-20 19:44 UTC by dranikpg

[issue](https://github.com/CrowCpp/Crow/issues/224)

2022-02-22 14:59 UTC, dranikpg commented on include/crow/middlewares/cors.h
> +            if (allow_credentials_) set_header("Access-Control-Allow-Credentials", "true", res);
Those are the most common CORS headers used (at least the first three).

2022-02-22 14:59 UTC, dranikpg commented on include/crow/middlewares/cors.h
> +        CORSRules& prefix(const std::string& prefix)
I though of using a more flexible builder like
```c++
cors
  .prefix("/foo")
    .origin()
    .header()
  .prefix("/bar")
    .origin()
    .header()
```
but clang-format doesn't like those and aligns all calls 😢 What do you think of those?Seems to be convenient

2022-02-22 14:59 UTC, dranikpg commented on include/crow/middlewares/cors.h
> +            for (auto& rule : rules)
I expect that there won't be more than a couple of prefixes, so linear search is okay. Something like a trie (there is no generic one in CROW) is a definite overkill.

2022-02-22 14:59 UTC, dranikpg commented on include/crow/middlewares/cors.h
> +                if (path.rfind(rule.first, 0) == 0)
that is STL's way of string.startsWith() 😆  Maybe I should comment this

2022-02-22 14:59 UTC, dranikpg commented on include/crow/middlewares/cors.h
> +            origin_ = origin;
We could elide copies here by making the code more complex. Given that this is called once on startup, I don't think its worth it

2022-02-22 14:59 UTC, dranikpg commented on include/crow/middlewares/cors.h
> +            if (!get_header_value(res.headers, key).empty()) return;
Headers are **not** overwritten, this means that a handler can change the CORS behaviour if it wants to

2022-03-04 02:05 UTC, The-EDev requested changes

2022-03-09 02:34 UTC, The-EDev approved these changes
Seems all good, merging now.

2022-03-09 02:34 UTC, merged