Add extra log when status code is not defined.
CrowCpp/Crow pull request #434
Opened 2022-05-08 11:54 UTC by konradkar2

Just to document behaviour when returning a status that is not well-known.
This issue could be fixed in a better way in the future, because for know it is only observed when using actual TCP connection - 
simple UT that uses app.handle(req, res) will return proper(user defined) status code.

Added some extra check on UT that caused segfault on my pc.

2022-05-08 13:04 UTC, The-EDev requested changes
Aside from the comments, it would be interesting to have some form of compile time check and warning for an unknown status code. Do you know if this is possible?

2022-05-08 16:26 UTC, konradkar2 commented on tests/unittest.cpp
> +        REQUIRE(res.headers.count("Content-Type"));
Actually I didn't notice that these are 2 different keys

2022-05-08 16:34 UTC, konradkar2 commented
> Aside from the comments and code formatting, it would be interesting to have some form of compile time check and warning for an unknown status code. Do you know if this is possible?

Well I think this is a bigger change, what do you think about merging this one, and then the proper implementation could be added as different feature (reverting this one I guess).

2022-05-08 17:44 UTC, The-EDev commented
> Well I think this is a bigger change, what do you think about merging this one, and then the proper implementation could be added as different feature (reverting this one I guess).

Yeah I agree with you, I'm just wondering if it was possible, since I couldn't find much info on doing it online.

2022-05-10 21:12 UTC, konradkar2 commented
> > Well I think this is a bigger change, what do you think about merging this one, and then the proper implementation could be added as different feature (reverting this one I guess).
> 
> Yeah I agree with you, I'm just wondering if it was possible, since I couldn't find much info on doing it online.

Well the problem with compile time check is that if we do it in crow::response then it will become hard to create response in runtime, or even make it impossible.

2022-05-10 21:14 UTC, konradkar2 commented
Btw. why are we using "45451" as port number in UTs? I've checked and port(0) results in random port, which is more robust I guess.

2022-05-10 22:56 UTC, The-EDev commented
It's more of a tradition, getting the app's port and setting the port to 0 were recent additions to crow (post `v0.3`). so the tests needed a port that was most likely not used and is predictable.

2022-05-11 21:05 UTC, The-EDev requested changes
Please replace `REQUIRE` with `CHECK` and an `if` statement in the unit tests, as a failing `REQUIRE` would prevent other tests from running.

Also CI seems to be exceeding the time limit (seems like some sort of blocking function / infinite loop)

2022-05-18 13:49 UTC, The-EDev approved these changes

2022-05-18 13:49 UTC, merged