Address #534 - handling missing mime types gracefully
CrowCpp/Crow pull request #536
Opened 2022-09-11 17:11 UTC by jake-arkinstall

Addresses #534.

My first Crow PR!

Please see the commit messages for the justification of my approach. I realise the addition of an additional header file might be controversial, but it seems to be the better of three evils.

2022-09-11 17:56 UTC, jake-arkinstall commented
Note: test is passing on amd64. On arm64, cloning fails due to insufficient storage.

2022-09-11 21:05 UTC, dranikpg requested changes
Great code & tests 👍🏻 Thanks a lot for implementing this

Just a single issue: lets really not introcude one more file for a minor issue - even if the request class becomes a bit larger.

I hope DroneCI will run successfully on your next push (it fails rarely). If not, I'll poke it a little till it runs :)

2022-09-12 11:15 UTC, dranikpg approved these changes

2022-09-12 11:16 UTC, merged

2022-09-12 11:16 UTC, dranikpg commented
Thanks!! 🎊 
It'll make it into 1.1