Handle _CROW_ILL or _CROW_ICD being NOTFOUND
CrowCpp/Crow pull request #720
Opened 2023-11-07 23:24 UTC by DavidPetkovsek

There is a big warning that may appear when compiling user code:
```
In file included from <built-in>:461:
<command line>:6:18: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
    6 | #define _CROW_ICD-NOTFOUND 1
      |
```

When using get_target_property in cmake and the property is not found it will define the content of the variable <var>-NOTFOUND and because these variables were being used as compile definitions it causes a bunch of warnings due to the `-` in the name.

### Solution:

If the variable is NOTFOUND then set it to "". Then at the end after possible list appends. If the variable is not "" then update the target properties. This means we do not add the compile definition at all.

This gets rid of a warning. And since there is nowhere in the code looking for NOTFOUND it does not change functionality.

2023-11-07 23:24 UTC, DavidPetkovsek commented
Fixes #661

2023-11-07 23:48 UTC, DavidPetkovsek commented
For those who want the patch for the latest release v1.0+5

[checkout this branch of the PR](https://github.com/DavidPetkovsek/Crow/tree/release-v1.0%2B5-update)

2023-12-22 13:31 UTC, DavidPetkovsek commented
The fix works for me. Lmk if there is an issue with anything.

2024-01-31 15:42 UTC, gittiver commented on cmake/CrowConfig.cmake.in
> +if(_CROW_ILL STREQUAL "_CROW_ILL-NOTFOUND")
We would not need to set the variables if we later on compare against the ..-NOTFOUND value.

2024-01-31 15:43 UTC, gittiver commented on cmake/CrowConfig.cmake.in
> +if( NOT (_CROW_ICD STREQUAL "" ) )
if (_CROW_ILL STREQUAL "_CROW_ILL-NOTFOUND")

2024-01-31 15:44 UTC, gittiver requested changes
Have a look at the proposed simplified version.

2024-02-01 01:33 UTC, DavidPetkovsek commented
> Have a look at the proposed simplified version.

Hi gittiver, thank you for the feed back!

We cannot follow through with those two changes.

For the first one. We need to set it to `""` because depending on what the user configures, the options later down will append items to the variables as a list. This would mean the "not found" would be a list item.

For the second one, we still need to check if empty because in another project I found if you try to add `""` it will cause something else to be added instead which depending on how cmake was used could cause an issue during configuration or building sometimes.

2024-02-02 14:14 UTC, gittiver commented
> We cannot follow through with those two changes.

I will have a look on the complete cmake files, I had just reviewed the changes.

2024-02-20 09:18 UTC, jbulow commented
Any update on this? The library is not usable in its current state:

```
<command line>:4:18: error: ISO C99 requires whitespace after the macro name [-Werror,-Wc99-extensions]
    4 | #define _CROW_ICD-NOTFOUND 1
      |                  ^
1 error generated.
```

2024-02-20 22:21 UTC, gittiver approved these changes

2024-02-20 22:22 UTC, gittiver commented
lets go with your solution.

2024-02-20 22:22 UTC, merged

2024-02-21 18:06 UTC, nam20485 commented
Anyone looking for a workaround to use prior to the release can be found in a comment in the accompanying issue:

https://github.com/CrowCpp/Crow/issues/661#issuecomment-1702544225