cmake install rules
CrowCpp/crow pull request #80
Opened 2020-12-05 07:23 UTC by ayaankhan98

To install *crow*  globally, one should run `make install` instead of `make` after `cmake ..` this will automatically copy `crow_all.h` to `/usr/local/include`. Thus making it available gloablly

2020-12-05 07:27 UTC, ayaankhan98 commented
This is what i understand after reading discussion of #68. Let me know if i am missing something or if this is fine i will add this in documentation too.

2020-12-05 10:51 UTC, The-EDev commented
If you want to link an issue in such a way that this PR closes it, you should look at https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2020-12-05 11:00 UTC, ayaankhan98 commented
> If you want to link an issue in such a way that this PR closes it, you should look at https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

yes i know this already, The reason i type it there is because i cannot link issue from the right cloumn of the web page. i don't know there may be some access rights issue which is not allowing me to link issue from there.

2020-12-05 11:04 UTC, The-EDev commented
Yes, you can link in issue by typing `closes #68` without needing the linked issues menu, whether you type that or add it from the menu, it should have the same effect

2020-12-05 11:07 UTC, ayaankhan98 commented
> Yes, you can link in issue by typing `closes #68` without needing the linked issues menu, whether you type that or add it from the menu, it should have the same effect

Thanks! got it.

2020-12-05 11:19 UTC, The-EDev submitted a review, later dismissed
Code seems to work fine.
You can add the documentation if you want or leave it to me.
If you choose to do it, you should explain the `make install` command as an alternative to `make` in line 97 of `docs/getting_started/setup.md` and explain what it does.

2020-12-05 11:26 UTC, ayaankhan98 commented
> Code seems to work fine.
> You can add the documentation if you want or leave it to me.
> If you choose to do it, you should explain the `make install` command as an alternative to `make` in line 97 of `docs/getting_started/setup.md` and explain what it does.

okay, will do that soon, once i do that you can thereafter give suggestions to improve upon that.

2020-12-06 12:28 UTC, The-EDev requested changes

2020-12-06 12:28 UTC, The-EDev commented on docs/getting_started/setup.md
>  ctest -V
This part should be above ##Installing Crow

2020-12-06 12:28 UTC, The-EDev commented on docs/getting_started/setup.md
> +if you wish to use crow globally without copying `crow_all.h` in your projects, you can install `crow` on your machine by using `make install` command instead of `make` after `cmake..`. Thus, the pro
maybe put Crow instead of `crow`, also the "instead of `make` after `cmake ..`" part is kind of redundant since the whole procedure is there

2020-12-06 12:28 UTC, The-EDev commented on docs/getting_started/setup.md
>  Running Cmake will create `crow_all.h` file and place it in the build directory.
make sure to add `<br>` between this and the test comment

2020-12-06 13:09 UTC, The-EDev requested changes

2020-12-06 13:09 UTC, The-EDev commented on docs/getting_started/setup.md
> +You can run tests with following commands:
seems like I accidentally wrote "commands" instead of "command"

2020-12-06 13:09 UTC, The-EDev commented on docs/getting_started/setup.md
> +if you wish to use crow globally without copying `crow_all.h` in your projects, you can install `Crow` on your machine with the following procedure below.
please remove the ``.
Also "the following procedure" and "the procedure below" mean the same thing, you can remove one

2020-12-06 13:42 UTC, The-EDev approved these changes

2020-12-06 13:42 UTC, merged