Add message view to avoid extra file copy
CrowCpp/crow pull request #82
Opened 2020-12-18 10:05 UTC by choice17

Add message_view in multipart.

It speed up HTTP POST files parsing using char ptr, while saving string in header.

2020-12-18 14:58 UTC, The-EDev commented
I'm not sure how this is works, @mrozigor can you please review this?

2020-12-20 08:04 UTC, mrozigor commented
Build fails. Is this used anywhere? Is it possible to measure performance boost? @choice17

2020-12-28 08:25 UTC, NobodyXu requested changes

2020-12-28 08:25 UTC, NobodyXu commented on include/crow/multipart.h
> +        struct sting_view
Typo: You probably means `string_view`.

2021-01-15 00:44 UTC, The-EDev commented
Closing this for lack of response, @choice17 feel free to still respond when you have time. Thanks.

2021-01-15 00:44 UTC, closed without merging