Make websocket close include the status code
CrowCpp/Crow pull request #854
Opened 2024-07-22 17:58 UTC by davidot

In the websocket protocol the first two bytes of the payload in a close packet indicate the status code.

:warning: This code is not backwards compatible, as I could not find how extreme we should do that. In the most extreme case we can use a std::enable_if on the onclose handler which then puts the status code in front of the message again to ensure any user code behaves the exact same.

2024-07-27 16:27 UTC, gittiver commented
HI davidot, could you update to the newest main branch? It's just for macOS build, which does not work anymore on macos11?

2024-07-27 16:45 UTC, gittiver commented on tests/unittest.cpp
> +        c.send(asio::buffer(close_message, 10));
size of close_message is 5 here?

2024-07-27 22:12 UTC, gittiver requested changes

2024-07-28 18:08 UTC, davidot commented on include/crow/websocket.h
> +            virtual void close(std::string const& msg = "quit", uint16_t status_code = 1000u) = 0;
Maybe but there are not limited to some fixed set as far as I can see.
Would you want to use an (non class) enum just to provide the default "recommended" codes?

2024-07-28 18:39 UTC, davidot commented on include/crow/websocket.h
> +                        close_handler_(*this, "uncleanly", 0);
Good point, will use the appropriate status code from the spec

2024-07-28 19:52 UTC, gittiver commented on include/crow/websocket.h
> +            virtual void close(std::string const& msg = "quit", uint16_t status_code = 1000u) = 0;
for the values, yes. I would like to have the default codes as enumeration.

2024-07-28 20:49 UTC, davidot commented
Rebased on master, added enum (non-class one, can change that) and fixed 0 codes.

CI failure is a already present unit test, although it is not failing on master? It is passing for me locally

2024-07-28 21:19 UTC, gittiver commented
Restarted the ci jobs, seems GitHub had an hiccup, all run successful (except windows which takes longer....)

2024-07-28 21:20 UTC, gittiver approved these changes

2024-07-29 07:41 UTC, gittiver requested changes
I just notized that documentation needs to be adapted.

2024-07-29 07:48 UTC, gittiver approved these changes

2024-07-29 08:20 UTC, merged